### ISSUE TITLE
设计一个schema来记录/预告每次salon

### ISSUE THREAD

**Issue by Thrimbda** [metacellar/salon#1]
目前是`日期` `话题` `主讲人` `论文列表`四列列表
是否可以有 `文档链接` `讨论记录` 等column，亟待讨论

**Comment by aak1247** [comment]
支持加文档链接（可以在里面包含一些QA）

**Comment by linxuyalun** [comment]
文档相关内容可以直接放到本 repo 下，同样包含分享的论文笔记，笔记不用拘泥于格式，也不用拘泥于长短，主要是对于论文的介绍或者思考（有思考最好）

另外需要考虑的是怎么记录 QA，或者有没有高效的记录 QA 的方式

同样还要考虑的是怎么组织我们 repo 的文档

**Comment by Thrimbda** [comment]
现在新添加了一个文档链接的 column
