### ISSUE TITLE
Topics expected

### ISSUE THREAD

**Issue by aak1247** [metacellar/salon#5]
Anything expected to share?

**Comment by Thrimbda** [comment]
real world software engineering cases.

1. how do you define a problem
2. how do you model a problem
3. how do you decompose the problem to simpler sub problems
4. how do you lead a team to solve the problem
5. how do you compose the solutions into a final one

**Comment by linxuyalun** [comment]
database

**Comment by aak1247** [comment]
> real world software engineering cases.
> 
> 1. how do you define a problem
> 2. how do you model a problem
> 3. how do you decompose the problem to simpler sub problems
> 4. how do you lead a team to solve the problem
> 5. how do you compose the solutions into a final one

ACK

**Comment by aak1247** [comment]
> database

ACK
