### ISSUE TITLE
Topic expected

### ISSUE THREAD

**Issue by linxuyalun** [metacellar/salon#6]
* Papers about the computer system
* Cloud Native related, for example, Istio
* Computer system engineering, for example, crash consistency, all or nothing, memory model, ROP...

**Comment by Thrimbda** [comment]
vote for istio, crash consistency

**Comment by Thrimbda** [comment]
network, network, network

**Comment by linxuyalun** [comment]
> network, network, network

accept

**Comment by linkinpark213** [comment]
> network, network, network

Okay, neural network👌

**Comment by linxuyalun** [comment]
Istio will be my next topic
