### ISSUE TITLE
Retro 议题

### ISSUE THREAD

**Issue by Thrimbda** [metacellar/salon#7]
请大家 propose retro 的议题。

我先来

1. 为连鸽两次做检讨，分析原因
2. 过去的几次分享哪些做得不好，为什么？
3. 过去的几次分享哪些做的好，简单分析一下原因？

**Comment by Thrimbda** [comment]
@linkinpark213 @linxuyalun @aak1247 @VanderChen @Jack-Q  PTAL

**Comment by linxuyalun** [comment]
1. 怎么解决先验知识不足的问题？比如在讲之前提前放一些材料？
2. 个人感觉整体还是拖沓了一些

**Comment by VanderChen** [comment]
1. 没有找到一个连贯的domain可以分享
2. 如何解决重数学的分享体验，使得能够听懂
